# Generated by Django 6.0.6 on 2026-09-16 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_challenge'),
        ('tournaments', '0002_section_tournamentregistration_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.section'),
        ),
    ]
