# Generated by Django 6.0.6 on 2026-09-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenger_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
