# Generated by Django 6.0.6 on 2026-09-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_challenge_challenger_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='eco',
            field=models.CharField(blank=True, help_text='ECO code from the PGN, e.g. B02', max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='opening',
            field=models.CharField(blank=True, help_text='Opening name from the PGN', max_length=120),
        ),
    ]
