# Generated by Django 6.0.6 on 2026-09-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'ordering': ['name'], 'verbose_name': 'club', 'verbose_name_plural': 'clubs'},
        ),
    ]
