# Generated by Django 6.0.6 on 2026-09-17 22:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0002_alter_association_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('source', models.CharField(default='Bulawayo Chess Hub', help_text='Who this came from. Shown as the byline.', max_length=120)),
                ('source_url', models.URLField(blank=True, help_text='Link to the original. Fill this in whenever the item is somebody else’s work, so credit is one click away.')),
                ('summary', models.TextField(help_text='One or two sentences. This is what shows on the news list.', max_length=400)),
                ('body', models.TextField(blank=True, help_text='The full item. Blank lines start new paragraphs. Leave it empty for a short notice that needs no page of its own.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, help_text='Leave empty for news that concerns everybody.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='associations.association')),
            ],
            options={
                'verbose_name': 'news item',
                'verbose_name_plural': 'news',
                'ordering': ['-published_at'],
            },
        ),
    ]
