# Generated by Django 6.0.6 on 2026-09-16 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('eligibility', models.CharField(blank=True, max_length=200)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='tournaments.section'),
        ),
    ]
