# Generated by Django 6.0.6 on 2026-09-16 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_totp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LichessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lichess_id', models.CharField(max_length=40, unique=True)),
                ('username', models.CharField(max_length=40)),
                ('title', models.CharField(blank=True, max_length=10)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('bullet_rating', models.IntegerField(blank=True, null=True)),
                ('bullet_games', models.PositiveIntegerField(default=0)),
                ('bullet_provisional', models.BooleanField(default=False)),
                ('blitz_rating', models.IntegerField(blank=True, null=True)),
                ('blitz_games', models.PositiveIntegerField(default=0)),
                ('blitz_provisional', models.BooleanField(default=False)),
                ('rapid_rating', models.IntegerField(blank=True, null=True)),
                ('rapid_games', models.PositiveIntegerField(default=0)),
                ('rapid_provisional', models.BooleanField(default=False)),
                ('total_games', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lichess', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
