# Generated by Django 6.0.6 on 2026-09-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-sent_at', '-pk']},
        ),
    ]
